### ISSUE TITLE
My Tax Bill broken?

### ISSUE THREAD

**Issue by sirrealist** [goinvo/visualbudget#108]
Can you quick check [visualbudget vis=mytaxbill]? 
Generated code is:

<div id='vb-chart-2c92ffc5' class='vb-chart vb-chart-mytaxbill' data-vb-dataset-url='/wp-content/plugins/visualbudget/datasets/.json' data-vb-vis="mytaxbill" data-vb-hash="2c92ffc5"></div>

Am I missing a dataset?

**Comment by rothos** [comment]
Fixed by #110
