### ISSUE TITLE
PHP version compatibility

### ISSUE THREAD

**Issue by sirrealist** [goinvo/visualbudget#60]
class-visualbudget.php line 44
define('VISUALBUDGET_PATH', $trailingslashit(dirname(**FILE**, 2)));
2nd parameter in dirname() is unsupported prior to PHP 7.
Many hosts don't provision PHP 7 yet.

WordPress is supported on PHP 5.6, so I suggest we use that as our compatibility base.

**Comment by rothos** [comment]
Thanks for reporting this. I'll fix it immediately.

**Comment by sirrealist** [comment]
I set PHP back down to 5.6 and just reported a new error – function random_int() is not in 5.6.

# 

Alan H. Jones
Carr-Jones, Inc.
jones@carr-jones.com
